# Generated by Django 6.0.5 on 2026-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
